import {
  BodyPosition,
  ContractionMode,
  ForceType,
  KineticChain,
  Laterality,
  MuscleRole,
  SkillLevel,
} from '../../../generated/prisma/client';

import type { ExerciseSeed } from '../types';
import { createExercise } from './create-exercise';

export const backExercises: ExerciseSeed[] = [
  {
    name: 'Pull-up',
    slug: 'pull-up',
    description:
      'A compound bodyweight vertical pulling exercise in which the body is raised toward an overhead bar.',
    instructions:
      'Hang from the bar with a pronated grip. Brace the trunk, initiate the movement by controlling the shoulder blades, and pull the elbows down toward the sides until the chin passes the bar or the upper chest approaches it. Lower under control to a full but stable hang.',
    commonMistakes:
      'Using uncontrolled momentum, excessively shrugging the shoulders, craning the neck over the bar, losing trunk position, or performing incomplete repetitions.',
    movementPatternSlug: 'vertical-pull',
    forceType: ForceType.PULL,
    kineticChain: KineticChain.CLOSED,
    isCompound: true,
    laterality: Laterality.BILATERAL,
    contractionMode: ContractionMode.DYNAMIC,
    bodyPosition: BodyPosition.OTHER,
    skillLevel: SkillLevel.INTERMEDIATE,
    imageAltText: 'Athlete performing a strict pull-up',
    equipmentSlugs: ['bodyweight', 'pull-up-bar'],
    muscles: [
      {
        muscleSlug: 'latissimus-dorsi',
        role: MuscleRole.PRIMARY,
        involvementScore: 5,
      },
      {
        muscleSlug: 'biceps-brachii',
        role: MuscleRole.SECONDARY,
        involvementScore: 4,
      },
      {
        muscleSlug: 'brachialis',
        role: MuscleRole.SECONDARY,
        involvementScore: 4,
      },
      {
        muscleSlug: 'teres-major',
        role: MuscleRole.SECONDARY,
        involvementScore: 3,
      },
      {
        muscleSlug: 'rhomboids',
        role: MuscleRole.SECONDARY,
        involvementScore: 3,
      },
      {
        muscleSlug: 'lower-trapezius',
        role: MuscleRole.SECONDARY,
        involvementScore: 3,
      },
      {
        muscleSlug: 'forearm-flexors',
        role: MuscleRole.STABILIZER,
        involvementScore: 4,
      },
      {
        muscleSlug: 'rotator-cuff',
        role: MuscleRole.STABILIZER,
        involvementScore: 2,
      },
    ],
    capabilities: {
      hypertrophyPotential: 5,
      maximalStrengthPotential: 4,
      powerDevelopmentPotential: 4,
      muscularEndurancePotential: 4,
      stabilityDevelopmentPotential: 3,
      typicalLoadability: 4,
      stretchPositionLoading: 4,
      shortenedPositionLoading: 4,
    },
    demands: {
      technicalDemand: 3,
      setupComplexity: 1,
      stabilityDemand: 3,
      systemicFatiguePotential: 3,
      localFatiguePotential: 4,
      recoveryCostPotential: 3,
      gripDemand: 4,
      axialLoadingPotential: 0,
    },
  },
  {
    name: 'Barbell Bent-over Row',
    slug: 'barbell-bent-over-row',
    description:
      'A compound horizontal pulling exercise performed while maintaining a hinged torso position.',
    instructions:
      'Hinge at the hips and hold the bar with the torso inclined forward. Brace the trunk, keep the spine controlled, and pull the bar toward the lower ribs by driving the elbows backward. Lower the bar under control without losing the hip-hinge position.',
    commonMistakes:
      'Rounding the lower back, standing progressively more upright, jerking the bar with hip momentum, excessively shrugging, or pulling the bar toward the neck.',
    movementPatternSlug: 'horizontal-pull',
    forceType: ForceType.PULL,
    kineticChain: KineticChain.OPEN,
    isCompound: true,
    laterality: Laterality.BILATERAL,
    contractionMode: ContractionMode.DYNAMIC,
    bodyPosition: BodyPosition.HINGED,
    skillLevel: SkillLevel.INTERMEDIATE,
    imageAltText: 'Athlete performing a barbell bent-over row',
    equipmentSlugs: ['barbell'],
    muscles: [
      {
        muscleSlug: 'latissimus-dorsi',
        role: MuscleRole.PRIMARY,
        involvementScore: 4,
      },
      {
        muscleSlug: 'middle-trapezius',
        role: MuscleRole.PRIMARY,
        involvementScore: 4,
      },
      {
        muscleSlug: 'rhomboids',
        role: MuscleRole.PRIMARY,
        involvementScore: 4,
      },
      {
        muscleSlug: 'posterior-deltoid',
        role: MuscleRole.SECONDARY,
        involvementScore: 3,
      },
      {
        muscleSlug: 'biceps-brachii',
        role: MuscleRole.SECONDARY,
        involvementScore: 3,
      },
      {
        muscleSlug: 'erector-spinae',
        role: MuscleRole.STABILIZER,
        involvementScore: 4,
      },
      {
        muscleSlug: 'forearm-flexors',
        role: MuscleRole.STABILIZER,
        involvementScore: 3,
      },
    ],
    capabilities: {
      hypertrophyPotential: 5,
      maximalStrengthPotential: 4,
      powerDevelopmentPotential: 3,
      muscularEndurancePotential: 3,
      stabilityDevelopmentPotential: 3,
      typicalLoadability: 4,
      stretchPositionLoading: 4,
      shortenedPositionLoading: 4,
    },
    demands: {
      technicalDemand: 4,
      setupComplexity: 2,
      stabilityDemand: 4,
      systemicFatiguePotential: 4,
      localFatiguePotential: 4,
      recoveryCostPotential: 4,
      gripDemand: 4,
      axialLoadingPotential: 3,
    },
  },
  createExercise({
    name: 'Conventional Deadlift',
    slug: 'conventional-deadlift',
    description:
      'A floor-start barbell hinge that develops whole-body pulling strength through coordinated leg drive, hip extension, and spinal bracing.',
    instructions:
      'Stand with midfoot under the bar, hinge to grip it, set the back, and brace before lifting. Push the floor away as the bar stays close, stand tall without leaning back, then hinge and bend the knees to return it under control.',
    commonMistakes:
      'Rounding the spine, jerking the bar from the floor, letting it drift forward, locking the knees too early, or hyperextending at lockout.',
    imageAltText: 'Athlete performing a conventional barbell deadlift',
    classification: [
      'hip-hinge',
      ForceType.PULL,
      KineticChain.MIXED,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.STANDING,
      SkillLevel.ADVANCED,
    ],
    equipmentSlugs: ['barbell', 'weight-plates'],
    muscles: [
      ['gluteus-maximus', MuscleRole.PRIMARY, 5],
      ['hamstrings', MuscleRole.PRIMARY, 4],
      ['erector-spinae', MuscleRole.SECONDARY, 4],
      ['quadriceps', MuscleRole.SECONDARY, 4],
      ['latissimus-dorsi', MuscleRole.STABILIZER, 3],
      ['forearm-flexors', MuscleRole.STABILIZER, 4],
    ],
    capabilityScores: [4, 5, 4, 2, 3, 5, 4, 3],
    demandScores: [4, 4, 4, 5, 4, 5, 5, 5],
  }),
  createExercise({
    name: 'Chin-up',
    slug: 'chin-up',
    description:
      'A supinated-grip bodyweight vertical pull that trains the lats and elbow flexors through a large closed-chain range.',
    instructions:
      'Hang from the bar with palms facing you, brace the trunk, and begin from controlled shoulders. Drive the elbows down to raise the upper chest toward the bar, then lower slowly to a full hang without swinging.',
    commonMistakes:
      'Kipping, craning the neck, losing shoulder control, stopping short of the bottom, or turning the movement into an uncontrolled curl.',
    imageAltText: 'Athlete performing a supinated-grip chin-up',
    classification: [
      'vertical-pull',
      ForceType.PULL,
      KineticChain.CLOSED,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.OTHER,
      SkillLevel.INTERMEDIATE,
    ],
    equipmentSlugs: ['bodyweight', 'pull-up-bar'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 5],
      ['biceps-brachii', MuscleRole.PRIMARY, 4],
      ['brachialis', MuscleRole.SECONDARY, 3],
      ['rhomboids', MuscleRole.SECONDARY, 3],
      ['lower-trapezius', MuscleRole.SECONDARY, 3],
      ['forearm-flexors', MuscleRole.STABILIZER, 3],
    ],
    capabilityScores: [5, 4, 3, 4, 4, 3, 4, 4],
    demandScores: [3, 1, 4, 3, 5, 3, 4, 0],
  }),
  createExercise({
    name: 'Neutral-grip Pull-up',
    slug: 'neutral-grip-pull-up',
    description:
      'A bodyweight vertical pull using parallel handles to train the lats, brachialis, and upper back with a shoulder-friendly grip.',
    instructions:
      'Take a neutral grip and hang with the ribs controlled. Pull by driving the elbows toward the hips until the chest approaches the handles, pause without shrugging, and lower to a controlled full hang.',
    commonMistakes:
      'Swinging, shortening the range, shrugging at the top, allowing the elbows to flare, or losing trunk tension.',
    imageAltText: 'Athlete performing a neutral-grip pull-up',
    classification: [
      'vertical-pull',
      ForceType.PULL,
      KineticChain.CLOSED,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.OTHER,
      SkillLevel.INTERMEDIATE,
    ],
    equipmentSlugs: ['bodyweight', 'pull-up-bar'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 5],
      ['brachialis', MuscleRole.SECONDARY, 4],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
      ['rhomboids', MuscleRole.SECONDARY, 3],
      ['lower-trapezius', MuscleRole.SECONDARY, 3],
      ['forearm-flexors', MuscleRole.STABILIZER, 3],
    ],
    capabilityScores: [5, 4, 3, 4, 4, 3, 4, 4],
    demandScores: [3, 1, 4, 3, 5, 3, 4, 0],
  }),
  createExercise({
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    description:
      'A seated cable vertical pull that provides scalable lat and upper-back loading without requiring full bodyweight strength.',
    instructions:
      'Secure the thighs under the pad, grip the bar outside shoulder width, and sit tall with a slight torso lean. Pull the elbows down until the bar nears the upper chest, then extend the arms slowly while keeping the shoulders controlled.',
    commonMistakes:
      'Pulling behind the neck, leaning back excessively, using momentum, shrugging, or stopping before full controlled arm extension.',
    imageAltText: 'Athlete performing a wide-grip lat pulldown',
    classification: [
      'vertical-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.SITTING,
      SkillLevel.BEGINNER,
    ],
    equipmentSlugs: ['lat-pulldown-machine'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 5],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
      ['teres-major', MuscleRole.SECONDARY, 3],
      ['rhomboids', MuscleRole.SECONDARY, 2],
      ['lower-trapezius', MuscleRole.SECONDARY, 2],
    ],
    capabilityScores: [5, 3, 2, 4, 2, 4, 5, 4],
    demandScores: [2, 1, 2, 2, 5, 2, 3, 0],
  }),
  createExercise({
    name: 'Single-arm Lat Pulldown',
    slug: 'single-arm-lat-pulldown',
    description:
      'A unilateral cable pulldown that allows focused lat loading and independent control of each shoulder blade.',
    instructions:
      'Kneel or sit beside a high pulley, brace the trunk, and begin with the working arm overhead. Pull the elbow down toward the hip without rotating, pause in the shortened position, and return slowly to a full reach.',
    commonMistakes:
      'Rotating the torso, turning the movement into a curl, shrugging, pulling past useful range, or rushing the return.',
    imageAltText: 'Athlete performing a single-arm cable lat pulldown',
    classification: [
      'vertical-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.UNILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.KNEELING,
      SkillLevel.BEGINNER,
    ],
    equipmentSlugs: ['cable-machine'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 5],
      ['teres-major', MuscleRole.SECONDARY, 3],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
      ['external-obliques', MuscleRole.STABILIZER, 2],
    ],
    capabilityScores: [5, 2, 1, 4, 3, 3, 5, 5],
    demandScores: [2, 2, 3, 1, 5, 2, 2, 0],
  }),
  createExercise({
    name: 'Pendlay Row',
    slug: 'pendlay-row',
    description:
      'A strict barbell row started from the floor each repetition to develop explosive horizontal pulling strength and upper-back force.',
    instructions:
      'Hinge until the torso is near parallel, brace firmly, and grip the bar on the floor. Pull it rapidly toward the lower chest without changing torso angle, lower it under control to a dead stop, and reset tension before the next rep.',
    commonMistakes:
      'Raising the torso during the pull, bouncing the bar, rounding the back, pulling toward the hips, or failing to reset between repetitions.',
    imageAltText: 'Athlete performing a Pendlay row from the floor',
    classification: [
      'horizontal-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.HINGED,
      SkillLevel.ADVANCED,
    ],
    equipmentSlugs: ['barbell', 'weight-plates'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 4],
      ['rhomboids', MuscleRole.PRIMARY, 4],
      ['middle-trapezius', MuscleRole.PRIMARY, 4],
      ['posterior-deltoid', MuscleRole.SECONDARY, 3],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
      ['erector-spinae', MuscleRole.STABILIZER, 4],
      ['forearm-flexors', MuscleRole.STABILIZER, 3],
    ],
    capabilityScores: [4, 4, 4, 2, 3, 4, 3, 3],
    demandScores: [4, 2, 4, 4, 4, 4, 4, 3],
  }),
  createExercise({
    name: 'Single-arm Dumbbell Row',
    slug: 'single-arm-dumbbell-row',
    description:
      'A supported unilateral row that develops the lats and scapular retractors while allowing a long pulling range.',
    instructions:
      'Support one hand and knee on a bench, square the hips, and let the dumbbell hang below the shoulder. Pull the elbow toward the hip without twisting, pause near the torso, and lower slowly to a controlled reach.',
    commonMistakes:
      'Rotating the torso, shrugging, yanking with momentum, pulling the elbow excessively high, or shortening the bottom range.',
    imageAltText: 'Athlete performing a single-arm dumbbell row',
    classification: [
      'horizontal-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.UNILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.HINGED,
      SkillLevel.BEGINNER,
    ],
    equipmentSlugs: ['dumbbells', 'bench'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 5],
      ['rhomboids', MuscleRole.SECONDARY, 4],
      ['middle-trapezius', MuscleRole.SECONDARY, 3],
      ['posterior-deltoid', MuscleRole.SECONDARY, 3],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
      ['forearm-flexors', MuscleRole.STABILIZER, 3],
    ],
    capabilityScores: [5, 3, 2, 4, 3, 4, 5, 4],
    demandScores: [2, 2, 3, 2, 5, 2, 4, 1],
  }),
  createExercise({
    name: 'Chest-supported Dumbbell Row',
    slug: 'chest-supported-dumbbell-row',
    description:
      'A prone incline-bench row that isolates the upper back and lats by removing most torso stabilization demands.',
    instructions:
      'Set a low incline, lie chest-down, and let the dumbbells hang with neutral wrists. Row the elbows toward the torso while keeping the chest on the pad, squeeze the shoulder blades, and lower to full arm extension.',
    commonMistakes:
      'Lifting the chest from the pad, shrugging, overextending the shoulders, using momentum, or cutting the bottom range short.',
    imageAltText: 'Athlete performing a chest-supported dumbbell row',
    classification: [
      'horizontal-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.PRONE,
      SkillLevel.BEGINNER,
    ],
    equipmentSlugs: ['dumbbells', 'adjustable-bench'],
    muscles: [
      ['rhomboids', MuscleRole.PRIMARY, 4],
      ['middle-trapezius', MuscleRole.PRIMARY, 4],
      ['latissimus-dorsi', MuscleRole.SECONDARY, 4],
      ['posterior-deltoid', MuscleRole.SECONDARY, 3],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
    ],
    capabilityScores: [5, 3, 2, 4, 1, 4, 5, 4],
    demandScores: [1, 2, 1, 1, 5, 2, 3, 0],
  }),
  createExercise({
    name: 'Seated Cable Row',
    slug: 'seated-cable-row',
    description:
      'A seated horizontal cable pull that trains the lats and scapular retractors with continuous resistance.',
    instructions:
      'Sit tall with feet braced and arms extended, keeping the spine neutral. Drive the elbows back to bring the handle toward the lower ribs, pause without leaning, and return slowly until the shoulder blades protract under control.',
    commonMistakes:
      'Rocking the torso, rounding the lower back, shrugging, pulling only with the arms, or allowing the weight stack to crash.',
    imageAltText: 'Athlete performing a seated cable row',
    classification: [
      'horizontal-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.SITTING,
      SkillLevel.BEGINNER,
    ],
    equipmentSlugs: ['cable-machine'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 4],
      ['rhomboids', MuscleRole.PRIMARY, 4],
      ['middle-trapezius', MuscleRole.PRIMARY, 4],
      ['posterior-deltoid', MuscleRole.SECONDARY, 3],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
    ],
    capabilityScores: [5, 3, 2, 4, 2, 4, 4, 5],
    demandScores: [2, 1, 2, 2, 5, 2, 3, 0],
  }),
  createExercise({
    name: 'T-bar Row',
    slug: 't-bar-row',
    description:
      'A landmine-supported barbell row that permits heavy horizontal pulling for the lats and mid-back.',
    instructions:
      'Straddle the anchored bar, hinge with a braced neutral spine, and grasp the handle near the sleeve. Pull toward the lower chest while keeping the torso stable, then lower the plates slowly to full arm extension.',
    commonMistakes:
      'Standing too upright, rounding the back, jerking the load, shrugging, or reducing range as weight increases.',
    imageAltText: 'Athlete performing a landmine T-bar row',
    classification: [
      'horizontal-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.HINGED,
      SkillLevel.INTERMEDIATE,
    ],
    equipmentSlugs: ['barbell', 'weight-plates', 'landmine-attachment'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 4],
      ['rhomboids', MuscleRole.PRIMARY, 4],
      ['middle-trapezius', MuscleRole.PRIMARY, 4],
      ['posterior-deltoid', MuscleRole.SECONDARY, 3],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
      ['erector-spinae', MuscleRole.STABILIZER, 3],
      ['forearm-flexors', MuscleRole.STABILIZER, 3],
    ],
    capabilityScores: [5, 4, 2, 3, 2, 5, 4, 4],
    demandScores: [3, 3, 3, 3, 5, 3, 4, 2],
  }),
  createExercise({
    name: 'Inverted Row',
    slug: 'inverted-row',
    description:
      'A closed-chain horizontal pull that develops upper-back strength and trunk control using adjustable body angle.',
    instructions:
      'Set a secure bar around waist height, hang beneath it with a straight body, and brace the glutes and trunk. Pull the chest toward the bar by retracting the shoulder blades, then lower under control to straight arms.',
    commonMistakes:
      'Sagging at the hips, leading with the chin, shrugging, shortening the pull, or losing body tension during the descent.',
    imageAltText: 'Athlete performing an inverted bodyweight row',
    classification: [
      'horizontal-pull',
      ForceType.PULL,
      KineticChain.CLOSED,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.OTHER,
      SkillLevel.BEGINNER,
    ],
    equipmentSlugs: ['bodyweight', 'squat-rack', 'barbell'],
    muscles: [
      ['rhomboids', MuscleRole.PRIMARY, 4],
      ['middle-trapezius', MuscleRole.PRIMARY, 4],
      ['latissimus-dorsi', MuscleRole.SECONDARY, 4],
      ['posterior-deltoid', MuscleRole.SECONDARY, 3],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
      ['transverse-abdominis', MuscleRole.STABILIZER, 3],
    ],
    capabilityScores: [4, 2, 2, 5, 4, 2, 3, 4],
    demandScores: [2, 2, 4, 2, 4, 2, 3, 0],
  }),
  createExercise({
    name: 'Straight-arm Cable Pulldown',
    slug: 'straight-arm-cable-pulldown',
    description:
      'A cable shoulder-extension exercise that isolates the lats while minimizing elbow-flexor contribution.',
    instructions:
      'Face a high pulley with arms extended and a slight hip hinge. Brace the ribs down, sweep the handle toward the thighs without bending the elbows, pause, and return slowly until the lats are lengthened overhead.',
    commonMistakes:
      'Turning it into a triceps press, rounding the spine, using torso momentum, shrugging, or stopping before the overhead stretch.',
    imageAltText: 'Athlete performing a straight-arm cable pulldown',
    classification: [
      'vertical-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.STANDING,
      SkillLevel.BEGINNER,
    ],
    equipmentSlugs: ['cable-machine'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 5],
      ['teres-major', MuscleRole.SECONDARY, 3],
      ['triceps-brachii', MuscleRole.STABILIZER, 2],
      ['transverse-abdominis', MuscleRole.STABILIZER, 2],
    ],
    capabilityScores: [5, 1, 1, 4, 2, 3, 5, 5],
    demandScores: [2, 1, 2, 1, 5, 2, 2, 0],
  }),
  createExercise({
    name: 'Dumbbell Pullover',
    slug: 'dumbbell-pullover',
    description:
      'A supine shoulder-extension exercise that loads the lats and chest through an overhead arc.',
    instructions:
      'Lie across or along a bench and hold one dumbbell above the chest with softly bent elbows. Keep the ribs controlled as the weight travels behind the head, stop at a comfortable stretch, and pull it back over the chest without changing elbow angle.',
    commonMistakes:
      'Hyperextending the lower back, bending and straightening the elbows, lowering beyond shoulder tolerance, moving too quickly, or losing grip security.',
    imageAltText: 'Athlete performing a dumbbell pullover on a bench',
    classification: [
      'vertical-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.SUPINE,
      SkillLevel.INTERMEDIATE,
    ],
    equipmentSlugs: ['dumbbells', 'bench'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 4],
      ['sternocostal-head-pectoralis-major', MuscleRole.SECONDARY, 3],
      ['teres-major', MuscleRole.SECONDARY, 3],
      ['triceps-brachii', MuscleRole.STABILIZER, 2],
      ['rectus-abdominis', MuscleRole.STABILIZER, 2],
    ],
    capabilityScores: [4, 2, 1, 3, 2, 3, 5, 3],
    demandScores: [3, 2, 3, 1, 4, 2, 3, 0],
  }),
  createExercise({
    name: 'Machine High Row',
    slug: 'machine-high-row',
    description:
      'A supported machine row with a high-to-low path that trains the lats, posterior shoulders, and scapular retractors.',
    instructions:
      'Adjust the seat and chest pad so the handles start above shoulder level. Keep the chest supported, pull the elbows down and back toward the ribs, pause, and return slowly to a full controlled reach.',
    commonMistakes:
      'Lifting away from the pad, shrugging, pulling with excessive elbow flexion, twisting, or letting the machine return abruptly.',
    imageAltText: 'Athlete using a plate-loaded high row machine',
    classification: [
      'horizontal-pull',
      ForceType.PULL,
      KineticChain.OPEN,
      true,
      Laterality.BILATERAL,
      ContractionMode.DYNAMIC,
      BodyPosition.SITTING,
      SkillLevel.BEGINNER,
    ],
    equipmentSlugs: ['row-machine'],
    muscles: [
      ['latissimus-dorsi', MuscleRole.PRIMARY, 5],
      ['posterior-deltoid', MuscleRole.SECONDARY, 4],
      ['rhomboids', MuscleRole.SECONDARY, 4],
      ['middle-trapezius', MuscleRole.SECONDARY, 3],
      ['biceps-brachii', MuscleRole.SECONDARY, 3],
    ],
    capabilityScores: [5, 3, 2, 4, 1, 4, 5, 4],
    demandScores: [1, 1, 1, 1, 5, 2, 3, 0],
  }),
];
