import type { MuscleFunctionSeed } from './types';

export const muscleFunctions: MuscleFunctionSeed[] = [
  {
    name: 'Shoulder horizontal adduction',
    slug: 'shoulder-horizontal-adduction',
    description: 'Moves the humerus across the body in the transverse plane.',
    sortOrder: 100,
  },
  {
    name: 'Shoulder flexion',
    slug: 'shoulder-flexion',
    description: 'Moves the humerus forward and upward in front of the body.',
    sortOrder: 200,
  },
  {
    name: 'Shoulder extension',
    slug: 'shoulder-extension',
    description: 'Moves the humerus backward behind the torso.',
    sortOrder: 300,
  },
  {
    name: 'Shoulder abduction',
    slug: 'shoulder-abduction',
    description: 'Moves the humerus away from the midline of the body.',
    sortOrder: 400,
  },
  {
    name: 'Shoulder internal rotation',
    slug: 'shoulder-internal-rotation',
    description: 'Rotates the humerus inward toward the body.',
    sortOrder: 500,
  },
  {
    name: 'Shoulder external rotation',
    slug: 'shoulder-external-rotation',
    description: 'Rotates the humerus outward away from the body.',
    sortOrder: 600,
  },
  {
    name: 'Shoulder stabilization',
    slug: 'shoulder-stabilization',
    description: 'Maintains control and position of the glenohumeral joint.',
    sortOrder: 700,
  },
  {
    name: 'Scapular protraction',
    slug: 'scapular-protraction',
    description: 'Draws the scapula forward around the rib cage.',
    sortOrder: 800,
  },
  {
    name: 'Scapular retraction',
    slug: 'scapular-retraction',
    description: 'Draws the scapula back toward the spine.',
    sortOrder: 900,
  },
  {
    name: 'Scapular elevation',
    slug: 'scapular-elevation',
    description: 'Raises the shoulder girdle.',
    sortOrder: 1000,
  },
  {
    name: 'Scapular depression',
    slug: 'scapular-depression',
    description: 'Lowers the shoulder girdle.',
    sortOrder: 1100,
  },
  {
    name: 'Scapular upward rotation',
    slug: 'scapular-upward-rotation',
    description: 'Rotates the scapula to support overhead motion.',
    sortOrder: 1200,
  },
  {
    name: 'Scapular stabilization',
    slug: 'scapular-stabilization',
    description: 'Maintains control and positioning of the scapula.',
    sortOrder: 1300,
  },
  {
    name: 'Elbow flexion',
    slug: 'elbow-flexion',
    description: 'Bends the elbow joint.',
    sortOrder: 1400,
  },
  {
    name: 'Elbow extension',
    slug: 'elbow-extension',
    description: 'Straightens the elbow joint.',
    sortOrder: 1500,
  },
  {
    name: 'Forearm supination',
    slug: 'forearm-supination',
    description: 'Turns the forearm so the palm faces upward.',
    sortOrder: 1600,
  },
  {
    name: 'Wrist flexion',
    slug: 'wrist-flexion',
    description: 'Bends the wrist toward the palm side.',
    sortOrder: 1700,
  },
  {
    name: 'Wrist extension',
    slug: 'wrist-extension',
    description: 'Lifts the back of the hand toward the forearm.',
    sortOrder: 1800,
  },
  {
    name: 'Grip assistance',
    slug: 'grip-assistance',
    description: 'Supports gripping and holding tasks at the hand and wrist.',
    sortOrder: 1900,
  },
  {
    name: 'Trunk flexion',
    slug: 'trunk-flexion',
    description: 'Bends the torso forward.',
    sortOrder: 2000,
  },
  {
    name: 'Trunk rotation',
    slug: 'trunk-rotation',
    description: 'Rotates the torso around its longitudinal axis.',
    sortOrder: 2100,
  },
  {
    name: 'Trunk lateral flexion',
    slug: 'trunk-lateral-flexion',
    description: 'Bends the torso sideways.',
    sortOrder: 2200,
  },
  {
    name: 'Abdominal compression',
    slug: 'abdominal-compression',
    description: 'Compresses and braces the abdominal wall.',
    sortOrder: 2300,
  },
  {
    name: 'Spinal stabilization',
    slug: 'spinal-stabilization',
    description: 'Maintains position and control of the spinal column.',
    sortOrder: 2400,
  },
  {
    name: 'Pelvic stabilization',
    slug: 'pelvic-stabilization',
    description: 'Helps keep the pelvis level and controlled.',
    sortOrder: 2500,
  },
  {
    name: 'Hip extension',
    slug: 'hip-extension',
    description: 'Moves the thigh backward at the hip joint.',
    sortOrder: 2600,
  },
  {
    name: 'Hip abduction',
    slug: 'hip-abduction',
    description: 'Moves the thigh away from the body midline.',
    sortOrder: 2700,
  },
  {
    name: 'Hip adduction',
    slug: 'hip-adduction',
    description: 'Moves the thigh toward the body midline.',
    sortOrder: 2800,
  },
  {
    name: 'Hip flexion',
    slug: 'hip-flexion',
    description: 'Lifts the thigh toward the torso.',
    sortOrder: 2900,
  },
  {
    name: 'Knee extension',
    slug: 'knee-extension',
    description: 'Straightens the knee joint.',
    sortOrder: 3000,
  },
  {
    name: 'Knee flexion',
    slug: 'knee-flexion',
    description: 'Bends the knee joint.',
    sortOrder: 3100,
  },
  {
    name: 'Ankle plantar flexion',
    slug: 'ankle-plantar-flexion',
    description: 'Points the foot downward away from the shin.',
    sortOrder: 3200,
  },
  {
    name: 'Ankle dorsiflexion',
    slug: 'ankle-dorsiflexion',
    description: 'Pulls the foot upward toward the shin.',
    sortOrder: 3300,
  },
  {
    name: 'Foot inversion',
    slug: 'foot-inversion',
    description: 'Turns the sole of the foot inward.',
    sortOrder: 3400,
  },
  {
    name: 'Cervical flexion',
    slug: 'cervical-flexion',
    description: 'Bends the neck forward.',
    sortOrder: 3500,
  },
  {
    name: 'Cervical rotation',
    slug: 'cervical-rotation',
    description: 'Rotates the head and neck.',
    sortOrder: 3600,
  },
  {
    name: 'Cervical stabilization',
    slug: 'cervical-stabilization',
    description: 'Maintains control of the neck and head position.',
    sortOrder: 3700,
  },
];
