import type { RoutineSeed } from './types';

export const pushRoutine = {
  key: 'push',
  name: 'Push',
  description:
    'A balanced push workout targeting the chest, shoulders, and triceps through horizontal and vertical pressing movements.',
  exercises: [
    {
      exerciseSlug: 'barbell-bench-press',
      order: 1,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes:
        'Use a controlled descent and maintain a stable pressing position.',
    },
    {
      exerciseSlug: 'incline-dumbbell-bench-press',
      order: 2,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes:
        'Use a moderate incline to emphasize the upper chest without excessively shifting the work to the shoulders.',
    },
    {
      exerciseSlug: 'dumbbell-shoulder-press',
      order: 3,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes: 'Keep the torso stable and avoid excessive lumbar extension.',
    },
    {
      exerciseSlug: 'cable-lateral-raise',
      order: 4,
      sets: 3,
      minReps: 12,
      maxReps: 20,
      targetRir: 1,
      restSeconds: 75,
      notes: 'Lead with the elbows and use a controlled range of motion.',
    },
    {
      exerciseSlug: 'cable-triceps-pushdown',
      order: 5,
      sets: 3,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 75,
      notes: 'Keep the upper arms fixed while extending the elbows.',
    },
    {
      exerciseSlug: 'overhead-cable-triceps-extension',
      order: 6,
      sets: 2,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 75,
      notes:
        'Allow a controlled stretch while keeping the shoulders and torso stable.',
    },
  ],
} as const satisfies RoutineSeed;

export const pullRoutine = {
  key: 'pull',
  name: 'Pull',
  description:
    'A balanced pull workout targeting the back, rear deltoids, biceps, brachialis, and forearms.',
  exercises: [
    {
      exerciseSlug: 'pull-up',
      order: 1,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes:
        'Use assistance or additional resistance as needed to remain within the target range.',
    },
    {
      exerciseSlug: 'chest-supported-dumbbell-row',
      order: 2,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes:
        'Pull the elbows backward without lifting the torso away from the support.',
    },
    {
      exerciseSlug: 'lat-pulldown',
      order: 3,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes: 'Drive the elbows downward and avoid excessive torso momentum.',
    },
    {
      exerciseSlug: 'cable-reverse-fly',
      order: 4,
      sets: 3,
      minReps: 12,
      maxReps: 20,
      targetRir: 1,
      restSeconds: 75,
      notes:
        'Move through the shoulders while maintaining a slight bend in the elbows.',
    },
    {
      exerciseSlug: 'incline-dumbbell-curl',
      order: 5,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 1,
      restSeconds: 75,
      notes: 'Keep the upper arms behind the torso and avoid swinging.',
    },
    {
      exerciseSlug: 'hammer-curl',
      order: 6,
      sets: 2,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 75,
      notes: 'Maintain a neutral grip and control the eccentric phase.',
    },
  ],
} as const satisfies RoutineSeed;

export const legsRoutine = {
  key: 'legs',
  name: 'Legs',
  description:
    'A complete lower-body workout covering the quadriceps, glutes, hamstrings, and calves through squat, hinge, and isolation movements.',
  exercises: [
    {
      exerciseSlug: 'barbell-back-squat',
      order: 1,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes:
        'Use a consistent depth that can be controlled without losing trunk or pelvic position.',
    },
    {
      exerciseSlug: 'romanian-deadlift',
      order: 2,
      sets: 3,
      minReps: 6,
      maxReps: 10,
      targetRir: 2,
      restSeconds: 150,
      notes:
        'Push the hips backward and stop before additional depth requires spinal movement.',
    },
    {
      exerciseSlug: 'leg-press',
      order: 3,
      sets: 3,
      minReps: 10,
      maxReps: 15,
      targetRir: 2,
      restSeconds: 120,
      notes:
        'Use the deepest controlled range that allows the pelvis to remain stable.',
    },
    {
      exerciseSlug: 'seated-leg-curl',
      order: 4,
      sets: 3,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 90,
      notes: 'Keep the hips secured against the seat throughout the set.',
    },
    {
      exerciseSlug: 'leg-extension',
      order: 5,
      sets: 2,
      minReps: 12,
      maxReps: 20,
      targetRir: 1,
      restSeconds: 75,
      notes: 'Control the lowering phase and avoid lifting the hips.',
    },
    {
      exerciseSlug: 'standing-calf-raise',
      order: 6,
      sets: 3,
      minReps: 8,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 75,
      notes: 'Pause briefly in both the stretched and shortened positions.',
    },
  ],
} as const satisfies RoutineSeed;

export const upperBodyRoutine = {
  key: 'upper-body',
  name: 'Upper Body',
  description:
    'A complete upper-body workout combining horizontal and vertical pushing and pulling with supplementary shoulder and arm work.',
  exercises: [
    {
      exerciseSlug: 'barbell-bench-press',
      order: 1,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes: 'Maintain a repeatable setup and stable contact with the bench.',
    },
    {
      exerciseSlug: 'pull-up',
      order: 2,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes:
        'Use assistance or additional resistance to remain within the target range.',
    },
    {
      exerciseSlug: 'dumbbell-shoulder-press',
      order: 3,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes: 'Keep the torso stable and avoid excessive spinal extension.',
    },
    {
      exerciseSlug: 'chest-supported-dumbbell-row',
      order: 4,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes:
        'Keep the chest supported while pulling the elbows behind the torso.',
    },
    {
      exerciseSlug: 'cable-lateral-raise',
      order: 5,
      sets: 2,
      minReps: 12,
      maxReps: 20,
      targetRir: 1,
      restSeconds: 60,
      notes: 'Use a controlled range and avoid shrugging.',
    },
    {
      exerciseSlug: 'cable-triceps-pushdown',
      order: 6,
      sets: 2,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 60,
      notes: 'Keep the upper arms stationary.',
    },
    {
      exerciseSlug: 'incline-dumbbell-curl',
      order: 7,
      sets: 2,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 60,
      notes: 'Avoid moving the upper arms forward during the curl.',
    },
  ],
} as const satisfies RoutineSeed;

export const lowerBodyRoutine = {
  key: 'lower-body',
  name: 'Lower Body',
  description:
    'A complete lower-body workout combining knee-dominant, hip-dominant, unilateral, hamstring, and calf movements.',
  exercises: [
    {
      exerciseSlug: 'barbell-back-squat',
      order: 1,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes:
        'Use a repeatable stance and the deepest range that can be controlled.',
    },
    {
      exerciseSlug: 'romanian-deadlift',
      order: 2,
      sets: 3,
      minReps: 6,
      maxReps: 10,
      targetRir: 2,
      restSeconds: 150,
      notes: 'Hinge through the hips while keeping the load close to the body.',
    },
    {
      exerciseSlug: 'bulgarian-split-squat',
      order: 3,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes: 'Complete all repetitions on one leg before switching sides.',
    },
    {
      exerciseSlug: 'seated-leg-curl',
      order: 4,
      sets: 3,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 90,
      notes:
        'Keep the hips secured against the seat and control the stretched position.',
    },
    {
      exerciseSlug: 'leg-extension',
      order: 5,
      sets: 2,
      minReps: 12,
      maxReps: 20,
      targetRir: 1,
      restSeconds: 75,
      notes:
        'Control both phases of the repetition and maintain a stable hip position.',
    },
    {
      exerciseSlug: 'standing-calf-raise',
      order: 6,
      sets: 3,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 75,
      notes: 'Use a full controlled range without bouncing.',
    },
  ],
} as const satisfies RoutineSeed;

export const fullBodyARoutine = {
  key: 'full-body-a',
  name: 'Full Body A',
  description:
    'A balanced full-body workout emphasizing the squat and horizontal press while covering all major movement patterns.',
  exercises: [
    {
      exerciseSlug: 'barbell-back-squat',
      order: 1,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes: 'Prioritize consistent depth and stable execution.',
    },
    {
      exerciseSlug: 'barbell-bench-press',
      order: 2,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes: 'Maintain a consistent setup and controlled touch point.',
    },
    {
      exerciseSlug: 'lat-pulldown',
      order: 3,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes: 'Drive the elbows downward without excessive torso movement.',
    },
    {
      exerciseSlug: 'romanian-deadlift',
      order: 4,
      sets: 2,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 150,
      notes: 'Use a controlled hip hinge and maintain a stable spine.',
    },
    {
      exerciseSlug: 'cable-lateral-raise',
      order: 5,
      sets: 2,
      minReps: 12,
      maxReps: 20,
      targetRir: 1,
      restSeconds: 60,
      notes: 'Keep the movement controlled and avoid shrugging.',
    },
    {
      exerciseSlug: 'cable-triceps-pushdown',
      order: 6,
      sets: 2,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 60,
      notes: 'Keep the upper arms stationary.',
    },
  ],
} as const satisfies RoutineSeed;

export const fullBodyBRoutine = {
  key: 'full-body-b',
  name: 'Full Body B',
  description:
    'A complementary full-body workout emphasizing the hip hinge and vertical press.',
  exercises: [
    {
      exerciseSlug: 'conventional-deadlift',
      order: 1,
      sets: 3,
      minReps: 4,
      maxReps: 6,
      targetRir: 2,
      restSeconds: 180,
      notes:
        'Keep the load balanced through the whole foot and maintain a braced torso.',
    },
    {
      exerciseSlug: 'standing-barbell-overhead-press',
      order: 2,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 150,
      notes: 'Keep the glutes and trunk engaged to limit lumbar extension.',
    },
    {
      exerciseSlug: 'chest-supported-dumbbell-row',
      order: 3,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes:
        'Maintain contact with the support and control the lowering phase.',
    },
    {
      exerciseSlug: 'bulgarian-split-squat',
      order: 4,
      sets: 2,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes: 'Complete all repetitions on one leg before switching sides.',
    },
    {
      exerciseSlug: 'incline-dumbbell-bench-press',
      order: 5,
      sets: 2,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 90,
      notes: 'Use a moderate incline and control the lowering phase.',
    },
    {
      exerciseSlug: 'hammer-curl',
      order: 6,
      sets: 2,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 60,
      notes: 'Maintain a neutral grip and avoid torso momentum.',
    },
  ],
} as const satisfies RoutineSeed;

export const fullBodyCRoutine = {
  key: 'full-body-c',
  name: 'Full Body C',
  description:
    'A full-body workout emphasizing unilateral lower-body work, upper-chest pressing, and vertical pulling.',
  exercises: [
    {
      exerciseSlug: 'barbell-front-squat',
      order: 1,
      sets: 3,
      minReps: 6,
      maxReps: 10,
      targetRir: 2,
      restSeconds: 180,
      notes: 'Maintain an upright torso and a stable front-rack position.',
    },
    {
      exerciseSlug: 'incline-dumbbell-bench-press',
      order: 2,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes:
        'Use a moderate incline and avoid allowing the shoulders to roll forward.',
    },
    {
      exerciseSlug: 'pull-up',
      order: 3,
      sets: 3,
      minReps: 6,
      maxReps: 10,
      targetRir: 2,
      restSeconds: 150,
      notes:
        'Use assistance or additional resistance to match the target range.',
    },
    {
      exerciseSlug: 'barbell-hip-thrust',
      order: 4,
      sets: 3,
      minReps: 8,
      maxReps: 12,
      targetRir: 2,
      restSeconds: 120,
      notes: 'Reach full hip extension without hyperextending the lower back.',
    },
    {
      exerciseSlug: 'single-arm-dumbbell-row',
      order: 5,
      sets: 2,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 75,
      notes:
        'Keep the torso stable while allowing controlled shoulder-blade movement.',
    },
    {
      exerciseSlug: 'overhead-cable-triceps-extension',
      order: 6,
      sets: 2,
      minReps: 10,
      maxReps: 15,
      targetRir: 1,
      restSeconds: 60,
      notes: 'Keep the elbows relatively fixed throughout the movement.',
    },
  ],
} as const satisfies RoutineSeed;

export const totalBodyStrengthRoutine = {
  key: 'total-body-strength',
  name: 'Total Body Strength',
  description:
    'A lower-volume total-body session centered on heavy compound movements and general strength development.',
  exercises: [
    {
      exerciseSlug: 'barbell-back-squat',
      order: 1,
      sets: 4,
      minReps: 3,
      maxReps: 5,
      targetRir: 2,
      restSeconds: 240,
      notes:
        'Prioritize repeatable technique and bar speed over maximal loading.',
    },
    {
      exerciseSlug: 'barbell-bench-press',
      order: 2,
      sets: 4,
      minReps: 3,
      maxReps: 5,
      targetRir: 2,
      restSeconds: 240,
      notes: 'Use a consistent setup and controlled touch point.',
    },
    {
      exerciseSlug: 'pull-up',
      order: 3,
      sets: 4,
      minReps: 4,
      maxReps: 6,
      targetRir: 2,
      restSeconds: 180,
      notes:
        'Use bodyweight or assistance when added resistance is not appropriate.',
    },
    {
      exerciseSlug: 'romanian-deadlift',
      order: 4,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 180,
      notes:
        'Use a controlled eccentric and stop before spinal position changes.',
    },
    {
      exerciseSlug: 'standing-barbell-overhead-press',
      order: 5,
      sets: 3,
      minReps: 5,
      maxReps: 8,
      targetRir: 2,
      restSeconds: 150,
      notes: 'Maintain a braced torso and finish with the arms overhead.',
    },
  ],
} as const satisfies RoutineSeed;

export const globalRoutines: readonly RoutineSeed[] = [
  pushRoutine,
  pullRoutine,
  legsRoutine,
  upperBodyRoutine,
  lowerBodyRoutine,
  fullBodyARoutine,
  fullBodyBRoutine,
  fullBodyCRoutine,
  totalBodyStrengthRoutine,
];
